-- Schema file
CREATE DATABASE IF NOT EXISTS telecom;
USE telecom;

CREATE TABLE IF NOT EXISTS users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100) UNIQUE NOT NULL,
 email VARCHAR(150) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL,
 mobile VARCHAR(20),
 role ENUM('customer','analyst','admin') DEFAULT 'customer',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plans (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 price DECIMAL(10,2) NOT NULL,
 data_gb INT NOT NULL,
 calls VARCHAR(50) NOT NULL,
 sms INT NOT NULL,
 validity_days INT NOT NULL
);

CREATE TABLE IF NOT EXISTS purchases (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 plan_id INT NOT NULL,
 plan_name VARCHAR(100),
 purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 expiry_date DATE,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS logs (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 action VARCHAR(255) NOT NULL,
 timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
